services:
  loki:
    image: grafana/loki:3.5.5
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
      - 7946
      - 9095

  tempo:
    image: grafana/tempo:2.8.2
    container_name: tempo
    restart: always
    command: ["-config.file=/etc/tempo.yaml"]
    expose:
      - 3200
      - 4317
      - 4318
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    restart: always
    ports:
      - 9008:9008
      - 9009:9009
    command: ["-config.file=/etc/mimir.yaml"]
    volumes:
      - ./config/mimir/mimir.yaml:/etc/mimir.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    command:
      [
        "--web.enable-remote-write-receiver",
        "--config.file=/etc/prometheus/prometheus.yaml",
      ]
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:12.1.1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_FORM_LOGIN=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    depends_on:
      - loki
      - tempo
      - mimir

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel
    restart: always
    ports:
      - 4317:4317 # gRPC
      - 4318:4318 # http
      - 8888:8888 # prometheus-collector
      - 8889:8889 # prometheus-exporter
      - 1888:1888 # pprof
      - 13133:13133 # health check
      - 55679:55679 # zpages
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/otel/otel.yaml:/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana

  promtail:
    image: grafana/promtail:3.5.5
    container_name: promtail
    restart: always
    volumes:
      - ./config/promtail/config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["-config.file=/etc/promtail/config.yaml"]
    depends_on:
      - loki
