auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  discover_log_levels: false

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: ++loki++
      s3forcepathstyle: true

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    s3: http://loki:++loki++@minio:9000/loki-data
    s3forcepathstyle: true
    insecure: true

compactor:
  working_directory: /loki/compactor

ruler:
  storage:
    type: s3
    s3:
      endpoint: minio:9000
      bucketnames: loki-ruler
      access_key_id: loki
      secret_access_key: ++loki++
      s3forcepathstyle: true
      insecure: true
